//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrbanMediMartMVCAzure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Order_detail = new HashSet<Order_detail>();
        }
    
        public int order_id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string shippingAddress { get; set; }
        public string ReciptantName { get; set; }
        public string ReciptantPhone { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<double> OrderTotal { get; set; }
        public string OrderStatus { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_detail> Order_detail { get; set; }
    }
}
