//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrbanMediMartMVCAzure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_detail
    {
        public int Order_detail_Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> Product_Id { get; set; }
        public int Quantity { get; set; }
        public double SubTotal { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
